{
 "title": "Quality Dashboard Demo",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Commits Per Week Past Year By Repo",
   "type": "graph",
   "description": "https://docs.github.com/en/rest/reference/metrics#get-the-last-year-of-commit-activity",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "repo" ], "type": "tag" }
     ],
     "measurement": "github_commits_per_week_past_year",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Open Pull Requests By Repo",
   "type": "graph",
   "description": "https://docs.github.com/en/rest/reference/repos",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "repo" ], "type": "tag" }
     ],
     "measurement": "github_issues",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Repo Commit Activity Per Week Heatmap Past Year",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "repo" ], "type": "tag" }
     ],
     "measurement": "github_commits_per_week_past_year",
     "query": "SELECT \"value\" FROM \"github_commits_per_week_past_year\" WHERE $timeFilter GROUP BY \"repo\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Open Issues with No Comments (Limit Recent 100)",
   "type": "gauge",
   "description": "https://docs.github.com/en/rest/reference/issues#list-repository-issues",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "repo" ], "type": "tag" }
     ],
     "measurement": "github_issues_no_comments",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}